# Generated by Django 3.0.3 on 2021-02-05 21:58

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=100)),
                ('Number', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('Class', models.IntegerField()),
                ('Course', models.CharField(max_length=30)),
                ('Information', models.TextField()),
            ],
        ),
    ]
