# Generated by Django 3.0.3 on 2021-02-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Information',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='Number',
            field=models.CharField(max_length=10),
        ),
    ]
